import { heroSpecSchema } from "@/wmotion/schemas/hero.schema";

export const demoHero = heroSpecSchema.parse({
  id: "wmotion-cinematic-25d-product-demo",
  renderer: "cinematic-25d",
  scrollLength: 430,
  brand: {
    name: "W Motion",
    primary: "#4a9dff",
    background: "#030712",
  },
  scenes: [
    { id: "arrival", start: 0, end: 0.34, transitionOut: "subject-push" },
    { id: "depth-shift", start: 0.34, end: 0.68, transitionIn: "subject-push", transitionOut: "light-pass" },
    { id: "reveal", start: 0.68, end: 1, transitionIn: "light-pass" },
  ],
  textTimeline: [
    {
      id: "intro-copy",
      from: 0.07,
      to: 0.25,
      eyebrow: "Cinematic 2.5D",
      headline: "Un soggetto. Una rivelazione.",
    },
    {
      id: "transition-copy",
      from: 0.40,
      to: 0.58,
      headline: "Lo scroll cambia la scena.",
      body: "Il soggetto avanza, la luce attraversa il frame e il visual si ricompone.",
    },
    {
      id: "final-copy",
      from: 0.76,
      to: 0.99,
      eyebrow: "W Motion Hero Engine",
      headline: "Asset reali. Movimento nativo.",
      body: "Nessun video necessario per costruire profondità, reveal e transizioni.",
      ctaLabel: "Step 3 attivo",
    },
  ],
  cinematic25d: {
    preset: "product-reveal",
    pointerStrength: 0.42,
    layers: [
      {
        id: "background",
        kind: "image",
        role: "background",
        depth: 0.02,
        parallax: 3,
        asset: {
          src: "/hero-assets/demo-bg.svg",
          alt: "",
          fit: "cover",
          position: "50% 50%",
          preload: true,
        },
        reveal: { type: "fade", from: 0, to: 0.08 },
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 1.04, opacity: 1 },
          { at: 0.55, x: -6, y: -4, scale: 1.12, opacity: 1 },
          { at: 1, x: 5, y: -10, scale: 1.2, opacity: 0.72 },
        ],
        mobile: { parallax: 1, scaleMultiplier: 1.08, position: "52% 50%" },
      },
      {
        id: "ambient-glow",
        kind: "glow",
        role: "effect",
        depth: 0.1,
        parallax: 5,
        blendMode: "screen",
        keyframes: [
          { at: 0, x: -10, y: -8, scale: 1.05, opacity: 0.25 },
          { at: 0.5, x: 14, y: 4, scale: 1.5, opacity: 0.72 },
          { at: 1, x: 0, y: -12, scale: 1.15, opacity: 0.3 },
        ],
      },
      {
        id: "subject",
        kind: "image",
        role: "subject",
        depth: 0.62,
        parallax: 24,
        asset: {
          src: "/hero-assets/demo-subject.svg",
          alt: "",
          fit: "contain",
          position: "50% 55%",
          preload: true,
        },
        visibility: { from: 0.05, to: 0.76 },
        reveal: { type: "wipe-x", from: 0.08, to: 0.25 },
        keyframes: [
          { at: 0, x: 130, y: 70, scale: 0.76, opacity: 0 },
          { at: 0.18, x: 58, y: 30, scale: 0.88, opacity: 1 },
          { at: 0.43, x: 4, y: 10, scale: 1.04, opacity: 1 },
          { at: 0.62, x: -38, y: -4, scale: 1.22, opacity: 1 },
          { at: 0.76, x: -160, y: -18, scale: 1.62, opacity: 0 },
          { at: 1, x: -220, y: -28, scale: 1.8, opacity: 0 },
        ],
        mobile: { parallax: 7, scaleMultiplier: 0.82, position: "50% 54%" },
      },
      {
        id: "foreground-atmosphere",
        kind: "image",
        role: "foreground",
        depth: 0.82,
        parallax: 26,
        blendMode: "screen",
        asset: {
          src: "/hero-assets/demo-foreground.svg",
          alt: "",
          fit: "cover",
          position: "50% 50%",
          preload: false,
        },
        visibility: { from: 0.12, to: 0.82 },
        reveal: { type: "fade", from: 0.12, to: 0.24 },
        keyframes: [
          { at: 0, x: -30, y: 35, scale: 1.02, opacity: 0 },
          { at: 0.35, x: 0, y: 12, scale: 1.08, opacity: 0.72 },
          { at: 0.68, x: 20, y: -6, scale: 1.16, opacity: 0.5 },
          { at: 1, x: 38, y: -18, scale: 1.22, opacity: 0 },
        ],
        mobile: { parallax: 5, scaleMultiplier: 1.12 },
      },
      {
        id: "light-pass",
        kind: "beam",
        role: "effect",
        depth: 0.92,
        parallax: 40,
        blendMode: "screen",
        visibility: { scenes: ["depth-shift"] },
        reveal: { type: "wipe-x", from: 0.42, to: 0.56 },
        keyframes: [
          { at: 0, x: -620, y: 100, scale: 0.7, opacity: 0 },
          { at: 0.40, x: -520, y: 55, scale: 0.82, opacity: 0 },
          { at: 0.52, x: -20, y: 8, scale: 1.02, opacity: 0.85, rotate: -8 },
          { at: 0.66, x: 520, y: -40, scale: 1.2, opacity: 0.2, rotate: -8 },
          { at: 1, x: 700, y: -80, scale: 1.3, opacity: 0 },
        ],
        mobile: { hidden: true },
      },
      {
        id: "final-ring",
        kind: "ring",
        role: "effect",
        depth: 0.36,
        parallax: 10,
        visibility: { scenes: ["reveal"] },
        reveal: { type: "circle", from: 0.68, to: 0.82 },
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 0.4, opacity: 0 },
          { at: 0.68, x: 0, y: 10, scale: 0.58, opacity: 0 },
          { at: 0.84, x: 0, y: -4, scale: 1.1, opacity: 0.72, rotate: 18 },
          { at: 1, x: 0, y: -12, scale: 1.4, opacity: 0.24, rotate: 34 },
        ],
        mobile: { parallax: 3, scaleMultiplier: 0.78 },
      },
      {
        id: "final-panel",
        kind: "panel",
        role: "effect",
        depth: 0.72,
        parallax: 18,
        visibility: { scenes: ["reveal"] },
        reveal: { type: "wipe-y", from: 0.71, to: 0.86 },
        keyframes: [
          { at: 0, x: 0, y: 80, scale: 0.88, opacity: 0 },
          { at: 0.7, x: 0, y: 60, scale: 0.9, opacity: 0 },
          { at: 0.86, x: 0, y: 16, scale: 1, opacity: 0.62 },
          { at: 1, x: 0, y: -2, scale: 1.04, opacity: 0.42 },
        ],
        mobile: { hidden: true },
      },
    ],
  },
  performance: {
    highRenderer: "cinematic-25d",
    mediumRenderer: "cinematic-25d",
    lowRenderer: "motion-2d",
  },
  responsive: {
    desktop: { scrollLength: 430, composition: "product-reveal-wide" },
    tablet: { scrollLength: 370, composition: "product-reveal-centered" },
    mobile: { scrollLength: 310, composition: "product-reveal-mobile" },
  },
});
