import { heroSpecSchema } from "@/wmotion/schemas/hero.schema";

export const demo3DHero = heroSpecSchema.parse({
  id: "wmotion-immersive-3d-demo",
  renderer: "immersive-3d",
  scrollLength: 470,
  brand: {
    name: "W Motion",
    primary: "#4a9dff",
    background: "#02050d",
  },
  scenes: [
    {
      id: "approach",
      start: 0,
      end: 0.32,
      transitionOut: "enter-ring",
    },
    {
      id: "crossing",
      start: 0.32,
      end: 0.68,
      transitionIn: "enter-ring",
      transitionOut: "subject-swap",
    },
    {
      id: "payoff",
      start: 0.68,
      end: 1,
      transitionIn: "subject-swap",
    },
  ],
  textTimeline: [
    {
      id: "intro",
      from: 0.06,
      to: 0.24,
      eyebrow: "Immersive 3D",
      headline: "Lo scroll muove la camera.",
    },
    {
      id: "transition",
      from: 0.42,
      to: 0.58,
      headline: "Attraversa. Cambia scena.",
      body: "La prospettiva resta continua mentre il soggetto cambia.",
    },
    {
      id: "payoff",
      from: 0.78,
      to: 0.99,
      eyebrow: "W Motion Hero Engine",
      headline: "Da A a B, nello stesso spazio.",
      ctaLabel: "Renderer 3D attivo",
    },
  ],
  immersive3d: {
    background: "#02050d",
    fog: {
      color: "#02050d",
      near: 7,
      far: 22,
    },
    camera: {
      pointerStrength: 0.22,
      keyframes: [
        {
          at: 0,
          position: [0, 0.4, 8.5],
          target: [0, 0, 0],
          fov: 48,
        },
        {
          at: 0.3,
          position: [0.4, 0.18, 5.1],
          target: [0, 0, 0],
          fov: 44,
        },
        {
          at: 0.52,
          position: [0.05, 0.05, 1.6],
          target: [0, 0, -1.5],
          fov: 52,
        },
        {
          at: 0.72,
          position: [-0.65, 0.25, -2.5],
          target: [0.4, 0, -5.2],
          fov: 46,
        },
        {
          at: 1,
          position: [0, 0.45, -6.6],
          target: [0, 0, -9],
          fov: 42,
        },
      ],
    },
    objects: [
      {
        id: "entry-orb",
        kind: "icosahedron",
        role: "subject",
        material: {
          color: "#4a9dff",
          metalness: 0.72,
          roughness: 0.18,
          emissive: "#0f4ea8",
          emissiveIntensity: 0.32,
          transparent: true,
          opacity: 1,
          wireframe: false,
        },
        visibility: {
          scenes: ["approach", "crossing"],
          from: 0,
          to: 0.58,
        },
        pointerInfluence: 0.16,
        keyframes: [
          {
            at: 0,
            position: [0, -0.1, 0],
            rotation: [-0.1, -0.45, 0],
            scale: [0.72, 0.72, 0.72],
            opacity: 0.5,
          },
          {
            at: 0.28,
            position: [0.3, 0.05, 0],
            rotation: [0.1, 0.4, 0.15],
            scale: [1, 1, 1],
            opacity: 1,
          },
          {
            at: 0.5,
            position: [-0.15, 0, -0.4],
            rotation: [0.35, 1.35, 0.4],
            scale: [1.45, 1.45, 1.45],
            opacity: 0.9,
          },
          {
            at: 0.62,
            position: [0, 0, -2.3],
            rotation: [0.6, 1.9, 0.7],
            scale: [2.2, 2.2, 2.2],
            opacity: 0,
          },
          {
            at: 1,
            position: [0, 0, -4],
            rotation: [0.8, 2.4, 0.9],
            scale: [2.4, 2.4, 2.4],
            opacity: 0,
          },
        ],
        mobile: {
          scaleMultiplier: 0.82,
        },
      },
      {
        id: "portal-ring",
        kind: "torus",
        role: "environment",
        material: {
          color: "#8bd0ff",
          metalness: 0.5,
          roughness: 0.22,
          emissive: "#2b7cff",
          emissiveIntensity: 1.2,
          transparent: true,
          opacity: 0.85,
          wireframe: false,
        },
        visibility: {
          from: 0.12,
          to: 0.78,
        },
        pointerInfluence: 0.06,
        keyframes: [
          {
            at: 0,
            position: [0, 0, -0.7],
            rotation: [0.15, 0.05, 0],
            scale: [0.75, 0.75, 0.75],
            opacity: 0,
          },
          {
            at: 0.3,
            position: [0, 0, -0.8],
            rotation: [0.1, 0.15, 0.2],
            scale: [1.2, 1.2, 1.2],
            opacity: 0.85,
          },
          {
            at: 0.52,
            position: [0, 0, -1],
            rotation: [0.05, 0.28, 0.45],
            scale: [2.4, 2.4, 2.4],
            opacity: 1,
          },
          {
            at: 0.72,
            position: [0, 0, -2.8],
            rotation: [0, 0.5, 0.8],
            scale: [3.8, 3.8, 3.8],
            opacity: 0.18,
          },
          {
            at: 1,
            position: [0, 0, -4],
            rotation: [0, 0.7, 1.1],
            scale: [4.2, 4.2, 4.2],
            opacity: 0,
          },
        ],
        mobile: {
          scaleMultiplier: 0.86,
        },
      },
      {
        id: "final-subject",
        kind: "sphere",
        role: "subject",
        material: {
          color: "#dcefff",
          metalness: 0.9,
          roughness: 0.12,
          emissive: "#12448f",
          emissiveIntensity: 0.16,
          transparent: true,
          opacity: 1,
          wireframe: false,
        },
        visibility: {
          scenes: ["payoff"],
          from: 0.62,
          to: 1,
        },
        pointerInfluence: 0.12,
        keyframes: [
          {
            at: 0,
            position: [0.7, 0.1, -8],
            rotation: [0, 0, 0],
            scale: [0.2, 0.2, 0.2],
            opacity: 0,
          },
          {
            at: 0.66,
            position: [0.7, 0.1, -7.2],
            rotation: [0.1, -0.3, 0],
            scale: [0.45, 0.45, 0.45],
            opacity: 0,
          },
          {
            at: 0.82,
            position: [0.35, 0, -8.3],
            rotation: [0.22, 0.35, 0.1],
            scale: [1, 1, 1],
            opacity: 1,
          },
          {
            at: 1,
            position: [0, 0.08, -9],
            rotation: [0.35, 0.7, 0.18],
            scale: [1.18, 1.18, 1.18],
            opacity: 1,
          },
        ],
        mobile: {
          scaleMultiplier: 0.74,
        },
      },
    ],
    lights: [
      {
        id: "ambient",
        type: "ambient",
        color: "#8bbcff",
        intensity: 0.55,
      },
      {
        id: "key",
        type: "directional",
        color: "#dcefff",
        intensity: 3.1,
        position: [4, 5, 6],
      },
      {
        id: "blue-rim",
        type: "point",
        color: "#277cff",
        intensity: 9,
        position: [-3, 1.5, 2],
      },
      {
        id: "rear-light",
        type: "point",
        color: "#78c9ff",
        intensity: 7,
        position: [2, -1, -7],
      },
    ],
    particles: {
      enabled: true,
      count: 320,
      spread: 15,
      size: 0.028,
      color: "#7ec8ff",
      opacity: 0.5,
    },
    pixelRatio: {
      high: 1.5,
      medium: 1,
      mobile: 1,
    },
  },
  cinematic25d: {
    preset: "spatial-ui",
    pointerStrength: 0.32,
    layers: [
      {
        id: "fallback-glow",
        kind: "glow",
        role: "background",
        depth: 0.08,
        parallax: 4,
        initial: {},
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 1, opacity: 0.45 },
          { at: 0.55, x: 8, y: -4, scale: 1.45, opacity: 0.7 },
          { at: 1, x: 0, y: -8, scale: 1.18, opacity: 0.32 },
        ],
      },
      {
        id: "fallback-ring",
        kind: "ring",
        role: "subject",
        depth: 0.6,
        parallax: 16,
        initial: {},
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 0.58, opacity: 0.42 },
          { at: 0.5, x: 0, y: 0, scale: 1.8, opacity: 0.95 },
          { at: 0.74, x: -18, y: -4, scale: 3.4, opacity: 0.08 },
          { at: 1, x: 0, y: -10, scale: 1.1, opacity: 0.38 },
        ],
        mobile: {
          parallax: 4,
          scaleMultiplier: 0.78,
        },
      },
    ],
  },
  performance: {
    highRenderer: "immersive-3d",
    mediumRenderer: "immersive-3d",
    lowRenderer: "cinematic-25d",
  },
  responsive: {
    desktop: {
      scrollLength: 470,
      composition: "immersive-space",
    },
    tablet: {
      scrollLength: 400,
      composition: "immersive-centered",
    },
    mobile: {
      scrollLength: 320,
      composition: "immersive-mobile",
    },
  },
});
