import { compileArtDirectionPlan } from "@/wmotion/art-director/compiler";
import { heroSpecSchema } from "@/wmotion/schemas/hero.schema";
import { halleMilanoPlan } from "./plan";

const base = compileArtDirectionPlan(halleMilanoPlan);

export const halleMilanoHero = heroSpecSchema.parse({
  ...base,
  id: "halle-milano-between-states",
  scrollLength: 360,
  brand: {
    name: "Halle",
    primary: "#f2efe7",
    background: "#0a0a09",
  },
  textTimeline: [
    {
      id: "intro-copy",
      from: 0.06,
      to: 0.22,
      eyebrow: "HALLE · MILANO",
      headline: "No fixed category.",
    },
    {
      id: "final-copy",
      from: 0.76,
      to: 0.99,
      eyebrow: "HALLE · MILANO",
      headline: "This, that and everything in between.",
      ctaLabel: "Book Now",
      ctaHref: "https://wa.me/3513211726",
    },
  ],
  motion2d: {
    background: "#0a0a09",
    preset: "kinetic-type",
    pointerStrength: 0.16,
    elements: [
      {
        id: "minimal",
        kind: "text",
        role: "subject",
        label: "MINIMAL",
        style: {
          color: "#f2efe7",
          fontSize: "clamp(4rem, 10vw, 10rem)",
          fontWeight: 760,
          letterSpacing: "-.06em",
          lineHeight: ".84",
          textAlign: "center",
          textTransform: "uppercase",
          mixBlendMode: "normal",
        },
        visibility: { from: 0, to: 0.48 },
        reveal: { type: "fade", from: 0.02, to: 0.13, invert: false },
        pointerInfluence: 0.08,
        keyframes: [
          { at: 0, x: -520, y: -105, scale: 0.82, opacity: 0 },
          { at: 0.16, x: -230, y: -105, scale: 0.94, opacity: 1 },
          { at: 0.32, x: -90, y: -58, scale: 1, opacity: 0.9 },
          { at: 0.48, x: -18, y: -18, scale: 1.05, opacity: 0 },
          { at: 1, x: 0, y: 0, scale: 1.05, opacity: 0 },
        ],
        mobile: {
          scaleMultiplier: 0.72,
          pointerInfluence: 0.02,
        },
      },
      {
        id: "punk",
        kind: "text",
        role: "subject",
        label: "PUNK",
        style: {
          color: "#d4d0c8",
          fontSize: "clamp(4rem, 12vw, 12rem)",
          fontWeight: 820,
          letterSpacing: "-.075em",
          lineHeight: ".82",
          textAlign: "center",
          textTransform: "uppercase",
          mixBlendMode: "normal",
        },
        visibility: { from: 0, to: 0.50 },
        reveal: { type: "fade", from: 0.04, to: 0.16, invert: false },
        pointerInfluence: 0.11,
        keyframes: [
          { at: 0, x: 560, y: 104, scale: 0.82, opacity: 0 },
          { at: 0.18, x: 250, y: 104, scale: 0.96, opacity: 1 },
          { at: 0.33, x: 96, y: 58, scale: 1.02, opacity: 0.92 },
          { at: 0.50, x: 18, y: 18, scale: 1.08, opacity: 0 },
          { at: 1, x: 0, y: 0, scale: 1.08, opacity: 0 },
        ],
        mobile: {
          scaleMultiplier: 0.72,
          pointerInfluence: 0.02,
        },
      },
      {
        id: "global",
        kind: "text",
        role: "effect",
        label: "GLOBAL",
        style: {
          color: "#a5a29c",
          fontSize: "clamp(2.4rem, 6vw, 6rem)",
          fontWeight: 560,
          letterSpacing: ".02em",
          lineHeight: ".9",
          textAlign: "center",
          textTransform: "uppercase",
          mixBlendMode: "normal",
        },
        visibility: { from: 0.26, to: 0.70 },
        reveal: { type: "wipe-x", from: 0.30, to: 0.42, invert: false },
        pointerInfluence: 0.06,
        keyframes: [
          { at: 0, x: -600, y: 155, scale: 0.8, opacity: 0 },
          { at: 0.34, x: -310, y: 155, scale: 0.9, opacity: 0.7 },
          { at: 0.54, x: -90, y: 64, scale: 1, opacity: 0.9 },
          { at: 0.66, x: -12, y: 12, scale: 1.04, opacity: 0.18 },
          { at: 1, x: 0, y: 0, scale: 1.04, opacity: 0 },
        ],
        mobile: {
          scaleMultiplier: 0.78,
          pointerInfluence: 0.01,
        },
      },
      {
        id: "local",
        kind: "text",
        role: "effect",
        label: "LOCAL",
        style: {
          color: "#a5a29c",
          fontSize: "clamp(2.4rem, 6vw, 6rem)",
          fontWeight: 560,
          letterSpacing: ".02em",
          lineHeight: ".9",
          textAlign: "center",
          textTransform: "uppercase",
          mixBlendMode: "normal",
        },
        visibility: { from: 0.26, to: 0.70 },
        reveal: { type: "wipe-x", from: 0.30, to: 0.42, invert: true },
        pointerInfluence: 0.06,
        keyframes: [
          { at: 0, x: 600, y: -155, scale: 0.8, opacity: 0 },
          { at: 0.34, x: 310, y: -155, scale: 0.9, opacity: 0.7 },
          { at: 0.54, x: 90, y: -64, scale: 1, opacity: 0.9 },
          { at: 0.66, x: 12, y: -12, scale: 1.04, opacity: 0.18 },
          { at: 1, x: 0, y: 0, scale: 1.04, opacity: 0 },
        ],
        mobile: {
          scaleMultiplier: 0.78,
          pointerInfluence: 0.01,
        },
      },
      {
        id: "halle-lockup",
        kind: "text",
        role: "subject",
        label: "HALLE",
        style: {
          color: "#f2efe7",
          fontSize: "clamp(6rem, 21vw, 22rem)",
          fontWeight: 860,
          letterSpacing: "-.095em",
          lineHeight: ".72",
          textAlign: "center",
          textTransform: "uppercase",
          mixBlendMode: "normal",
        },
        visibility: { from: 0.39, to: 1 },
        reveal: { type: "circle", from: 0.40, to: 0.56, invert: false },
        pointerInfluence: 0.045,
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 0.44, opacity: 0 },
          { at: 0.40, x: 0, y: 0, scale: 0.58, opacity: 0 },
          { at: 0.56, x: 0, y: 0, scale: 1, opacity: 1 },
          { at: 0.68, x: 0, y: -6, scale: 1.04, opacity: 0.94 },
          { at: 0.78, x: 0, y: -16, scale: 1.10, opacity: 0.12 },
          { at: 1, x: 0, y: -20, scale: 1.14, opacity: 0.06 },
        ],
        mobile: {
          scaleMultiplier: 0.70,
          pointerInfluence: 0.01,
        },
      },
      {
        id: "horizontal-axis",
        kind: "line",
        role: "effect",
        style: {
          width: "min(86vw, 1280px)",
          height: "1px",
          background: "rgba(242,239,231,.34)",
          borderRadius: "999px",
          mixBlendMode: "normal",
        },
        visibility: { from: 0.08, to: 0.68 },
        reveal: { type: "wipe-x", from: 0.08, to: 0.24, invert: false },
        pointerInfluence: 0,
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 0.2, opacity: 0 },
          { at: 0.24, x: 0, y: 0, scale: 1, opacity: 0.52 },
          { at: 0.54, x: 0, y: 0, scale: 1, opacity: 0.32 },
          { at: 0.68, x: 0, y: 0, scale: 0.2, opacity: 0 },
          { at: 1, x: 0, y: 0, scale: 0.2, opacity: 0 },
        ],
        mobile: {
          scaleMultiplier: 0.86,
          pointerInfluence: 0,
        },
      },
      {
        id: "vertical-axis",
        kind: "line",
        role: "effect",
        style: {
          width: "min(74vh, 760px)",
          height: "1px",
          background: "rgba(242,239,231,.18)",
          borderRadius: "999px",
          mixBlendMode: "normal",
        },
        visibility: { from: 0.20, to: 0.64 },
        reveal: { type: "wipe-x", from: 0.20, to: 0.36, invert: false },
        pointerInfluence: 0,
        keyframes: [
          { at: 0, x: 0, y: 0, scale: 0.2, rotate: 90, opacity: 0 },
          { at: 0.36, x: 0, y: 0, scale: 1, rotate: 90, opacity: 0.34 },
          { at: 0.54, x: 0, y: 0, scale: 1, rotate: 90, opacity: 0.22 },
          { at: 0.64, x: 0, y: 0, scale: 0.2, rotate: 90, opacity: 0 },
          { at: 1, x: 0, y: 0, scale: 0.2, rotate: 90, opacity: 0 },
        ],
        mobile: {
          hidden: true,
          scaleMultiplier: 1,
          pointerInfluence: 0,
        },
      },
      {
        id: "final-frame",
        kind: "panel",
        role: "background",
        label: "",
        style: {
          width: "min(82vw, 1180px)",
          height: "min(64vh, 680px)",
          background: "rgba(255,255,255,0)",
          borderColor: "rgba(242,239,231,.14)",
          borderWidth: 1,
          borderRadius: "0px",
          mixBlendMode: "normal",
        },
        visibility: { from: 0.62, to: 1 },
        reveal: { type: "fade", from: 0.62, to: 0.78, invert: false },
        pointerInfluence: 0.015,
        keyframes: [
          { at: 0, x: 0, y: 38, scale: 0.90, opacity: 0 },
          { at: 0.62, x: 0, y: 30, scale: 0.92, opacity: 0 },
          { at: 0.78, x: 0, y: 0, scale: 1, opacity: 0.48 },
          { at: 1, x: 0, y: -4, scale: 1.01, opacity: 0.28 },
        ],
        mobile: {
          scaleMultiplier: 0.84,
          pointerInfluence: 0,
        },
      },
    ],
  },
  performance: {
    highRenderer: "motion-2d",
    mediumRenderer: "motion-2d",
    lowRenderer: "motion-2d",
  },
  responsive: {
    desktop: {
      scrollLength: 360,
      composition: "opposing-kinetic-type",
    },
    tablet: {
      scrollLength: 320,
      composition: "centered-kinetic-type",
    },
    mobile: {
      scrollLength: 270,
      composition: "stacked-kinetic-type",
    },
  },
});
