import { artDirectionPlanSchema } from "@/wmotion/art-director/schemas";

export const halleMilanoPlan = artDirectionPlanSchema.parse({
  version: "1.0",
  projectId: "halle-milano-hero",
  brand: {
    name: "Halle",
    analysis: {
      corePromise: "Give people a space where hair and identity can move beyond fixed categories.",
      desiredEmotion: "recognition, curiosity and creative confidence",
      proofToImply: "Halle understands individuality as culture, not just as a hairstyle.",
      visualOpportunity: "Use Halle's own opposing identity pairs as the raw material of a kinetic editorial hero.",
      visualRisks: [
        "looking like a generic luxury salon",
        "turning Berlin references into cliché club visuals",
        "using too much copy",
        "making cultural positioning feel detached from booking",
      ],
      conversionPrinciple: "Create immediate identification with the Halle worldview, then resolve cleanly into Book Now.",
    },
  },
  objective: {
    conversionGoal: "Book an appointment",
    primaryCta: "Book Now",
  },
  concept: {
    name: "Between States",
    oneSentenceIdea: "Opposing identity words move from separate edges of the frame, overlap and finally lock into a single HALLE composition.",
    visualMetaphor: "Halle is the space between fixed categories rather than one side of them.",
    heroMoment: "Minimal, punk, global and local collapse into one precise typographic alignment and HALLE becomes the only stable center.",
    heroMomentProgress: 0.56,
    noveltyReason: "The visual system is built directly from Halle's own community manifesto instead of generic hair imagery or salon effects.",
  },
  renderer: {
    recommended: "motion-2d",
    reason: "The concept is fundamentally editorial and typographic, so lightweight kinetic type expresses the brand more authentically than simulated depth or 3D.",
    fallback: "motion-2d",
  },
  artDirection: {
    preset: "neutral",
    composition: "High-contrast full-screen typography with opposing words entering from different axes and HALLE resolving in the center.",
    colorDirection: "Near-black background, bone-white typography and restrained neutral greys; no generic beauty gradients.",
    typographyDirection: "Oversized condensed-feeling grotesk treatment, tight tracking and aggressive editorial scale shifts.",
    motionLanguage: "Linear slides, opposing directions, abrupt alignment and controlled deceleration at the hero moment.",
    depthStrategy: "Imply shallow depth only through scale, overlap and pointer offset; keep the experience essentially flat and graphic.",
  },
  scenes: [
    {
      id: "opposites",
      purpose: "hook",
      description: "Minimal and punk occupy opposite sides of the frame while a thin axis divides the composition.",
      from: 0,
      to: 0.30,
      subject: "contrasting identity words",
      motionIntent: "Words enter from opposing horizontal directions with restrained pointer response.",
      textIntent: "No fixed category.",
      transitionOut: "categories-cross",
    },
    {
      id: "between",
      purpose: "payoff",
      description: "Global and local cross through the first pair and all categories align around HALLE.",
      from: 0.30,
      to: 0.68,
      subject: "HALLE identity",
      motionIntent: "Category words converge while HALLE scales into a stable central lockup.",
      transitionOut: "identity-resolves",
    },
    {
      id: "book",
      purpose: "conversion",
      description: "The category words disappear and HALLE recedes into a quiet final branded frame with booking CTA.",
      from: 0.68,
      to: 1,
      subject: "final Halle identity frame",
      motionIntent: "Visual noise reduces and the final message becomes dominant.",
    },
  ],
  assets: [
    {
      id: "identity-words",
      role: "subject",
      type: "css",
      purpose: "Kinetic typography representing Halle's opposing identity pairs.",
      sourceStrategy: "procedural",
      mobileStrategy: "simplify",
      priority: "critical",
    },
    {
      id: "axis-system",
      role: "effect",
      type: "css",
      purpose: "Thin graphic axes that organize and then disappear as the words align.",
      sourceStrategy: "procedural",
      mobileStrategy: "simplify",
      priority: "important",
    },
    {
      id: "identity-frame",
      role: "background",
      type: "css",
      purpose: "Minimal editorial frame behind the resolved HALLE identity.",
      sourceStrategy: "procedural",
      mobileStrategy: "crop",
      priority: "important",
    },
  ],
  copy: {
    eyebrow: "HALLE · MILANO",
    headline: "This, that and everything in between.",
    supportingLine: "Cut, color and identity without fixed categories.",
    cta: "Book Now",
  },
  mobileStrategy: {
    compositionChange: "Stack the opposing words vertically around a centered HALLE lockup and shorten all horizontal travel.",
    motionSimplification: "Reduce pointer response, remove one axis line and keep only two opposing word pairs before the final resolve.",
    hiddenAssetIds: [],
    targetScrollLengthVh: 270,
  },
  performanceStrategy: {
    high: "Full kinetic typography, two axis lines and subtle pointer offset.",
    medium: "Same Motion 2D renderer with lower pointer influence and reduced travel distance.",
    low: "Static HALLE lockup, short fade between contrast words and immediate Book Now CTA.",
    maxCriticalAssets: 2,
  },
});
