import { clientResearchBundleSchema } from "@/wmotion/workflow/schemas";

export const halleMilanoResearch = clientResearchBundleSchema.parse({
  projectId: "halle-milano-hero",
  requestedUrl: "https://hallemilano.com/",
  canonicalUrl: "https://www.hallemilano.com/",
  pages: [
    {
      url: "https://www.hallemilano.com/",
      title: "Halle",
      sourceType: "official-website",
      purpose: "identity",
      notes: [
        "Homepage presents HALLE, Book now, Pricelist, Gift Cards, Team, Halle Zine and RAUM.",
        "Book now is the clearest conversion action in the main navigation.",
      ],
    },
    {
      url: "https://www.hallemilano.com/team/",
      title: "Team — Halle",
      sourceType: "official-website",
      purpose: "about",
      notes: [
        "Davide Omizzolo is described as a color specialist and stylist focused on genderless cuts and color contrasts.",
        "Current imagery/aesthetic inspiration is described through Nippo-Berlin street style and fashion.",
      ],
    },
    {
      url: "https://www.hallemilano.com/no-gender-pricelist/",
      title: "Pricelist — Halle",
      sourceType: "official-website",
      purpose: "services",
      notes: [
        "Pricelist confirms design cuts, treatments, styling, color, toner, highlights, balayage, bleaching and keratin services.",
      ],
    },
    {
      url: "https://www.hallemilano.com/halle-zine/",
      title: "Halle Zine",
      sourceType: "official-website",
      purpose: "visual",
      notes: [
        "The Zine is built around Halle's community and Milan's emerging new generation.",
        "The official manifesto celebrates individuality and contrasts such as minimalist/punk, global/local and business/party.",
      ],
    },
    {
      url: "https://www.hallemilano.com/halle-raum/",
      title: "Halle RAUM",
      sourceType: "official-website",
      purpose: "visual",
      notes: [
        "RAUM presents emerging creatives and positions Halle beyond a conventional salon-only identity.",
      ],
    },
    {
      url: "https://www.treatwell.it/salone/halle-milano/",
      title: "Halle.Milano — Treatwell",
      sourceType: "secondary-source",
      purpose: "location",
      notes: [
        "Secondary source identifies the salon at Via Mantova 17, Milano and confirms hair services.",
      ],
    },
  ],
  facts: [
    {
      field: "brandName",
      value: "Halle",
      sourceUrl: "https://www.hallemilano.com/",
      status: "explicit",
      confidence: "high",
      rationale: "The official homepage identifies the brand as HALLE.",
    },
    {
      field: "businessType",
      value: "Hair studio with a connected cultural and creative program",
      sourceUrl: "https://www.hallemilano.com/team/",
      status: "inferred",
      confidence: "medium",
      rationale: "Team and service pages establish hairstyling, while Zine and RAUM extend the identity into community and art.",
    },
    {
      field: "location",
      value: "Via Mantova 17, Milano",
      sourceUrl: "https://www.treatwell.it/salone/halle-milano/",
      status: "explicit",
      confidence: "medium",
      rationale: "The location is stated by a current secondary business listing.",
    },
    {
      field: "offer",
      value: "Genderless cuts, color, bleaching and styling with a strong identity-led approach",
      sourceUrl: "https://www.hallemilano.com/team/",
      status: "inferred",
      confidence: "medium",
      rationale: "The team page explicitly mentions genderless cuts and color contrasts, reinforced by the service list.",
    },
    {
      field: "servicesOrProducts",
      value: "Design cuts",
      sourceUrl: "https://www.hallemilano.com/no-gender-pricelist/",
      status: "explicit",
      confidence: "high",
      rationale: "Design cuts are listed directly in the official pricelist.",
    },
    {
      field: "servicesOrProducts",
      value: "Color and toner services",
      sourceUrl: "https://www.hallemilano.com/no-gender-pricelist/",
      status: "explicit",
      confidence: "high",
      rationale: "Color, toner, highlights and balayage are listed directly.",
    },
    {
      field: "servicesOrProducts",
      value: "Bleaching services",
      sourceUrl: "https://www.hallemilano.com/no-gender-pricelist/",
      status: "explicit",
      confidence: "high",
      rationale: "Multiple bleaching services are listed directly.",
    },
    {
      field: "audience",
      value: "Style-conscious people who value individuality, experimentation and contemporary culture",
      sourceUrl: "https://www.hallemilano.com/halle-zine/",
      status: "inferred",
      confidence: "medium",
      rationale: "The Zine explicitly centers a community, Milan's emerging new generation and the celebration of individuality.",
    },
    {
      field: "conversionGoal",
      value: "Book an appointment",
      sourceUrl: "https://www.hallemilano.com/",
      status: "inferred",
      confidence: "medium",
      rationale: "Book now is the clearest primary action exposed in the main navigation.",
    },
    {
      field: "primaryCta",
      value: "Book Now",
      sourceUrl: "https://www.hallemilano.com/",
      status: "explicit",
      confidence: "high",
      rationale: "Book now appears directly in the official homepage navigation.",
    },
    {
      field: "brandTraits",
      value: "genderless",
      sourceUrl: "https://www.hallemilano.com/team/",
      status: "explicit",
      confidence: "high",
      rationale: "Davide's profile explicitly references genderless cuts.",
    },
    {
      field: "brandTraits",
      value: "experimental",
      sourceUrl: "https://www.hallemilano.com/team/",
      status: "inferred",
      confidence: "medium",
      rationale: "Color contrasts, street-style references and the broader creative program support an experimental identity.",
    },
    {
      field: "brandTraits",
      value: "community-led",
      sourceUrl: "https://www.hallemilano.com/halle-zine/",
      status: "explicit",
      confidence: "high",
      rationale: "The official Zine states an intention to create community, connections and dialogue.",
    },
    {
      field: "brandTraits",
      value: "culture-connected",
      sourceUrl: "https://www.hallemilano.com/halle-raum/",
      status: "explicit",
      confidence: "high",
      rationale: "RAUM hosts emerging creatives and exhibitions.",
    },
    {
      field: "visualIdentityNotes",
      value: "Nippo-Berlin street style and fashion references",
      sourceUrl: "https://www.hallemilano.com/team/",
      status: "explicit",
      confidence: "high",
      rationale: "These influences are explicitly named in Davide's team profile.",
    },
    {
      field: "visualIdentityNotes",
      value: "Editorial community photography is already part of the brand language",
      sourceUrl: "https://www.hallemilano.com/halle-zine/",
      status: "explicit",
      confidence: "high",
      rationale: "The Zine is an official commissioned photographic project around Halle's community.",
    },
    {
      field: "visualOpportunities",
      value: "Turn Halle's opposing identity pairs into a kinetic editorial system that resolves into one brand",
      sourceUrl: "https://www.hallemilano.com/halle-zine/",
      status: "inferred",
      confidence: "medium",
      rationale: "The official Zine deliberately describes Halle through contrasting pairs.",
    },
    {
      field: "availableAssets",
      value: "Halle Zine community photography",
      sourceUrl: "https://www.hallemilano.com/halle-zine/",
      status: "explicit",
      confidence: "high",
      rationale: "The official Zine contains commissioned photography.",
    },
    {
      field: "availableAssets",
      value: "Team imagery",
      sourceUrl: "https://www.hallemilano.com/team/",
      status: "explicit",
      confidence: "high",
      rationale: "The official team page includes team imagery.",
    },
    {
      field: "currentSiteFriction",
      value: "The homepage exposes several strong worlds—services, team, Zine and RAUM—but the textual hierarchy does not immediately unify them into one dominant brand proposition",
      sourceUrl: "https://www.hallemilano.com/",
      status: "inferred",
      confidence: "medium",
      rationale: "The homepage distributes attention across several destinations without an explicit unifying proposition in the crawled content.",
    },
    {
      field: "preserve",
      value: "Book Now as the primary conversion action",
      sourceUrl: "https://www.hallemilano.com/",
      status: "explicit",
      confidence: "high",
      rationale: "It is already a primary navigation action.",
    },
    {
      field: "preserve",
      value: "The relationship between hair, community and emerging creative culture",
      sourceUrl: "https://www.hallemilano.com/halle-zine/",
      status: "inferred",
      confidence: "medium",
      rationale: "Zine and RAUM make this broader cultural layer central to Halle's identity.",
    }
  ],
  unresolvedQuestions: [
    "The official site crawl does not expose a formal brand color palette.",
    "The final production hero should ideally use original Halle logo and approved photographic assets.",
  ],
  researchNotes: [
    "Core business and brand claims rely on first-party sources.",
    "Treatwell is used only as supporting location evidence.",
  ],
});
